modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="random"
version="1.0.0"
displayName="R.A.N.D.O.M"
displayURL="https://github.com/RubensLixo/R.A.N.D.O.M-Mod"
credits="https://github.com/RubensLixo/R.A.N.D.O.M-Mod"
authors="BuildersDream, PotatoKingOfGods"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.random]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.random]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.random]]
modId="curios_api"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.random]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration